version: "3.5"

services:

  jupyter:
    build: ./docker/jupyter
    restart: unless-stopped
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
      - "8051:8050"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  api:
    build: ./docker/django
    command: sh /entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./data:/data
    ports:
      - "8080:8000"
      - "9999:9999"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    image: postgis/postgis:12-3.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  injects_anomalies_wl:
    build:
      context: ./docker/injects_anomalies_wl/
      dockerfile: ./Dockerfile
    ports:
      - "8050:8050"