# Generated by Django 3.1.3 on 2021-02-06 18:59

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_add_projectlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Success'), (2, 'Training'), (3, 'Error')], null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=17, max_digits=18)),
                ('precision', models.DecimalField(blank=True, decimal_places=17, max_digits=18)),
                ('recall', models.DecimalField(blank=True, decimal_places=17, max_digits=18)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=17, max_digits=18)),
                ('confusion_matrix', models.TextField(blank=True)),
                ('serialized_prediction_file', models.FileField(null=True, upload_to=web.models.serialized_prediction_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
