# Generated by Django 3.1.3 on 2020-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201203_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(default='New Label'),
        ),
    ]
