# Generated by Django 3.1.3 on 2020-12-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201203_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataset',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.project'),
        ),
    ]
