# Generated by Django 3.1.3 on 2021-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_projectfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprediction',
            name='input_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectprediction',
            name='skip_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectprediction',
            name='target_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectprediction',
            name='timestamp_features',
            field=models.TextField(null=True),
        ),
    ]
