# Generated by Django 3.1.3 on 2020-12-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201209_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='project_id',
            new_name='project',
        ),
    ]
