# Generated by Django 3.1.3 on 2021-03-02 10:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_add_fields_projectprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprediction',
            name='confusion_matrix_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=17, max_digits=18), blank=True, null=True, size=None),
        ),
    ]
