# Generated by Django 3.1.3 on 2021-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_projectprediction_confusion_matrix_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Complete'), (0, 'Incomplete')], null=True),
        ),
    ]
