# Generated by Django 3.1.3 on 2020-12-14 14:37

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201211_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.FileField(null=True, upload_to=web.models.user_directory_path),
        ),
    ]
