# Generated by Django 3.1.3 on 2021-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_source', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('model_prediction', models.IntegerField(blank=True, choices=[(1, 'Precipitation Rain Forest'), (2, 'Water Level LSTM')], null=True)),
                ('data', models.TextField()),
                ('result', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
