# Generated by Django 3.1.3 on 2020-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201214_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delimiter',
            field=models.CharField(default=',', max_length=3),
        ),
    ]
