# Generated by Django 3.1.3 on 2021-01-04 13:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_project_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
