# Generated by Django 3.1.3 on 2021-04-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210403_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiData',
        ),
    ]
