# Generated by Django 3.1.3 on 2021-01-04 13:58

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210104_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
