# Generated by Django 3.1.3 on 2021-01-04 14:02

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210104_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF', '#FFFF00']),
        ),
    ]
