# Generated by Django 3.1.3 on 2021-04-29 00:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_delete_apidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprediction',
            name='expected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=50, max_digits=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectprediction',
            name='predicted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=50, max_digits=100), blank=True, null=True, size=None),
        ),
    ]
