# Generated by Django 3.1.3 on 2021-04-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210429_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprediction',
            name='confusion_matrix',
        ),
    ]
