# Generated by Django 3.1.3 on 2021-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_projectparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparameters',
            name='default',
            field=models.TextField(null=True),
        ),
    ]
