# Generated by Django 3.1.3 on 2021-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_projectparameters_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprediction',
            name='parameters',
            field=models.TextField(null=True),
        ),
    ]
